### ISSUE TITLE
I'm unable to test specific contracts.

### ISSUE THREAD

**Issue by akhilmanga** [Cyfrin/foundry-upgrades-f23#4]
<img width="676" alt="Screenshot 2023-07-28 at 4 52 09 PM" src="https://github.com/Cyfrin/foundry-upgrades-f23/assets/116151859/71a3a00d-1ef6-416f-838b-87dbca83ec36">

I don't have bash. 

I have a question => What is bash? How to install it? How can i use it?

Actually i have seen sir patrick recommended to watch bash tutorial in previous lessons. But i only want to know overview of bash. (Any recommendations?)

**Comment by PatrickAlphaC** [comment]
Use `--mt` now, they upgraded foundry. 

`bash` is a command line shell. If you're using a mac, you're either using a `bash` or `zsh` terminal. 

Sure! FreeCodeCamp has a great bash scripting tutorial.
