### ISSUE TITLE
Upgrade Error

### ISSUE THREAD

**Issue by moayaan1911** [Cyfrin/foundry-upgrades-f23#8]
![Screenshot 2023-11-13 005308](https://github.com/Cyfrin/foundry-upgrades-f23/assets/95223782/4985406d-829c-400a-bc8e-814f96c085ac)
I am getting this error again and again. I searched on chatgpt, made some changes but still not working, so I reverted back. Please help me. 
[My github repo link](https://github.com/moayaan1911/solidity-full/tree/main/11.FoundryUpgradableContracts)

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Could you please remember to follow this section to format your questions? https://youtu.be/umepbfKp5rI?t=22464
