### ISSUE TITLE
Makefile gives wrong version 

### ISSUE THREAD

**Issue by S23Web3** [Cyfrin/foundry-upgrades-f23#9]
The makefile installs version 5 of openzeppelin. There could be no issue at all (as I am still in the module) however I wanted to point it out. 

![Screenshot from 2024-02-20 16-39-27](https://github.com/Cyfrin/foundry-upgrades-f23/assets/150437497/ecb2d2fe-8eb8-4bf4-ba92-dbe44a0b72c0)
I don't want to be annoying but here I just went from the makefile and as you can see it went for the version 5 of openzeppelin (Installed openzeppelin-contracts-upgradeable v5.0.1) instead of the version that you were pointing at in the video (4.8.3)

Just wanted to let you know and let me know what I can do to help out.

**Comment by S23Web3** [comment]
The new path is added to a sub map,
`import {UUPSUpgradeable} from "lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol";`

I am writing this in case an aspiring security researcher/ dev would get openzeppelin v5 installed. I came across issues when installing and de-installing and re-installing a lower version so that is why. Hope it would help for those who need it.

**Comment by PatrickAlphaC** [comment]
Good call! I have fixed this here.

https://github.com/Cyfrin/foundry-upgrades-f23/commit/b349a69ae360aec609cd6a27243d56eea60f1f9f

**Comment by S23Web3** [comment]
Thanks so much,

note for those who installed version 5, in the UUPSUpgradable contract the function upgradeTo is not present anymore so you probably get an error:
```Error: 
Compiler run failed:

Error (9582): Member "upgradeTo" not found or not visible after argument-dependent lookup in contract BoxV1.

--> script/UpgradeBox.s.sol:32:9:

   |
32 |         proxy.upgradeTo(address(newBox));
   |         ^^^^^^^^^^^^^^^
```
in `lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol`

```solidity
function upgradeTo(address newImplementation) public virtual onlyProxy {
        _authorizeUpgrade(newImplementation);
        _upgradeToAndCallUUPS(newImplementation, new bytes(0));
    }
```
Add this, it is similar to upgradeToAndCall but lacks the data (bytes) parameter
//edited in the resolve in case someone did update to v5 and gets an error, I removed false as the 3rd argument, this might give additional bugs as _upgradeToAndCallUUPS is a mystery for now. If it doesn't matter then for now won't add anything.

//2nd edit, tests passed with version 5 as instructed in the lesson with adding the function above in UUPSUpgradeable, not being stubborn with the version just testing if it works for a fellow student to find a solution if overlooked installing the matching version (4.8.x) of openzeppelin
